config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'products#index'
  resources :products do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show,:index] do
    collection do
      get 'search'
    end
  end
  resources :items, only: [:create]
  resources :stylegenres,  only:[:index,:show] do
    collection do
      get 'search'
    end
  end
    


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :products

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :products

end

app/models/perm.rb
class Perm < ApplicationRecord
  has_many :products

end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :video, VideoUploader
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :item
  belongs_to :color
  belongs_to :perm
  belongs_to :stylegenre 
  validates :text, presence: true
  validates :shop_name, presence: true
  validates :stylest_name, presence: true
  validates :video, presence: true




end

app/models/stylegenre.rb
class Stylegenre < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
      has_many :products
      has_one :item, dependent: :destroy
      validates :nickname, presence: true, length: { maximum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :move_to_index, except: [:index,:show]

  def index
    @bob_style =  Product.where(stylegenre_id: 1).order("id DESC").limit(3)
    @short_style = Product.where(stylegenre_id: 2).order("id DESC").limit(3)
    @mid_style = Product.where(stylegenre_id: 3).order("id DESC").limit(3)
    @semlong_style = Product.where(stylegenre_id: 4).order("id DESC").limit(3)
    @long_style = Product.where(stylegenre_id: 5).order("id DESC").limit(3)
    @superlong_style = Product.where(stylegenre_id: 6).order("id DESC").limit(3)
    @hairset_style = Product.where(stylegenre_id: 7).order("id DESC").limit(3)

    
  end

  def new 
    @product = Product.new
    

  end

  def create
    Product.create(product_params)
    redirect_to root_path

  end

  def edit
    @product = Product.find(params[:id])

  end

  def update
    product = Product.find(params[:id])
    if product.user_id == current_user.id
      product.update(link_url:product_params[:link_url],shop_name:product_params[:shop_name],video:product_params[:video],text:product_params[:text],item_id:product_params[:item_id],cosme:product_params[:cosme],stylegenre_id:params[:stylegenre_id],color_id:params[:color_id],perm_id:params[:perm_id],user_id: current_user.id)
    end
    redirect_to root_path
  end

  def destroy
    product = Product.find(params[:id])
    if product.user_id == current_user.id
      product.delete
      redirect_to root_path
    end
  end

  def show
    @product = Product.find(params[:id])
    @item = Item.find(@product.item_id)
    @color = Color.find(@product.color_id)
    @perm = Perm.find(@product.perm_id)
    @stylegenre = Stylegenre.find(@product.stylegenre_id)
  end

  def search
    @products = Product.includes(:user).page(params[:page]).per(9).order("created_at DESC")
  end

  
  private

  def product_params
    params.require(:product).permit(:title,:link_url,:shop_name,:video,:text,:stylest_name,:cosme).merge(stylegenre_id:params[:stylegenre_id],color_id:params[:color_id],perm_id:params[:perm_id],item_id: params[:item_id],user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/stylegenres_controller.rb
class StylegenresController < ApplicationController
  def show
    genre = Stylegenre.find(params[:id])
    @name = genre.name
    @products = genre.products.includes(:stylegenre).page(params[:page]).per(9).order("created_at DESC")
  end

  def search
    
  end

  def index
    @genres = Stylegenre.where('name LIKE(?)',"%#{params[:keyword]}%").limit(15)

    respond_to do |format|
      format.html
      format.json
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @products = user.products.includes(:user).page(params[:page]).per(9).order("created_at DESC")
  end

  def search
  end

  def index
    @users = User.where('nickname LIKE(?)',"%#{params[:keyword]}%").limit(15)

    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stylegenres_helper.rb
module StylegenresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NextBeauty
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
  .header
    .header-name
      = link_to "Next-Beauty",root_path
      - if user_signed_in?
        = link_to "ログアウト" ,destroy_user_session_path, method: :delete,class:"header-link"
        = link_to "マイページ","/users/#{current_user.id}", method: :get,class:"header-link"
        = link_to "スタイル一覧" ,search_products_path,class:"header-link"
        = link_to "ユーザー検索",search_users_path,class:"header-link"

      - else
        = link_to "ログイン",new_user_session_path,class:"log-btn"
        = link_to "新規登録",new_user_registration_path,class:"log-btn"
  %body
    = yield

app/views/products/_footer.html.haml
.app-banner
  .footer-new
    -if user_signed_in?
      = link_to new_product_path, class: "footer-new-btn" do
        .footer-new-btn__text
          掲載する
        %i.fas.fa-video.footer-btn__icon
    -else
      = link_to new_user_session_path, class: "footer-new-btn" do
        .footer-new-btn__text
          掲載する
        %i.fas.fa-video.footer-btn__icon

app/views/products/edit.html.haml
.edit-contents
  = form_for  @product do |f|
    .edit-one
      %h3 編集する
      .edit-form
        = f.label :タイトル（必須）,class:"edit-label"
        = f.text_field :title,class:"edit-text-box"
      .error-edit-11
      .edit-form
        = f.label :店名（必須）,class:"edit-label"
        = f.text_field :shop_name,class:"edit-text-box"
      .error-edit-1
      .edit-form
        = f.label :説明文（必須）,class:"edit-label"
        = f.text_field :text,class:"edit-text-box"
      .error-edit-2
      .edit-form
        = f.label :動画（必須）,class:"edit-label"
        = f.file_field :video,class:"video-edit"
      .error-edit-3
      .edit-form
        = f.label :スタイリスト名（必須）,class:"edit-label"
        = f.text_field :stylest_name,class:"edit-text-box"
      .error-edit-4
      .edit-form
        = f.label :コスメ,class:"edit-label"
        = f.text_field :cosme,class:"edit-text-box"
      .error-edit-5
      .edit-form
        = f.label :リンク,class:"edit-label"
        = f.text_field :link_url,class:"edit-text-box"
      .error-edit-6
      .edit-item-form
        = f.label :スタイル（必須）,class:"edit-select-label"
        %select.edit-stylename-select-box{name: "stylegenre_id"}
          %option{value: ""} ----
          %option{value: 1} ボブ
          %option{value: 2} ショート
          %option{value: 3} ミディアム
          %option{value: 4} セミロング
          %option{value: 5} ロング
          %option{value: 6} スーパーロング
          %option{value: 7} ヘアセット
      .error-edit-7
      .edit-item-form
        = f.label :アイテム（必須）,class:"edit-select-label"
        %select.edit-items-select-box{name: "item_id"}
          %option{value: ""} ----
          %option{value: 1} ストレートアイロン
          %option{value: 2} コテ32mm
          %option{value: 3} コテ28mm
          %option{value: 4} コテ18mm
          %option{value: 5} コテ16mm
          %option{value: 6} ロールブラシ
          %option{value: 7} デンマンブラシ
          %option{value: 8} ドライヤー
          %option{value: 9} クルクルドライヤー
          %option{value: 10} Uピンorアメピン
          %option{value: 11} ヘアゴム         
          %option{value: 12} なし 
      .error-edit-8
      .edit-item-form
        = f.label :カラー（必須）,class:"edit-select-label"
        %select.edit-items-select-box{name: "color_id"}
          %option{value: ""} ----
          %option{value: 1} 12LV；アッシュ系
          %option{value: 2} 10LV；アッシュ系
          %option{value: 3} 8LV；アッシュ系
          %option{value: 4} 6LV；アッシュ系
          %option{value: 5} 12LV；バイオレッド系
          %option{value: 6} 10LV；バイオレッド系
          %option{value: 7} 8LV；バイオレッド系
          %option{value: 8} 6LV；バイオレッド系
          %option{value: 9} 12LV；イエロー系
          %option{value: 10} 10LV；イエロー系
          %option{value: 11} 8LV；イエロー系
          %option{value: 12} 6LV；イエロー系
          %option{value: 13} 12LV；ピンク系
          %option{value: 14} 10LV；ピンク系
          %option{value: 15} 8LV；ピンク系
          %option{value: 16} 6LV；ピンク系
          %option{value: 17} 12LV；レッド系
          %option{value: 18} 10LV；レッド系
          %option{value: 19} 8LV；レッド系
          %option{value: 20} 6LV；レッド系
          %option{value: 21} 12LV；ブラウン系
          %option{value: 22} 10LV；ブラウン系
          %option{value: 23} 8LV；ブラウン系
          %option{value: 24} 6LV；ブラウン系
          %option{value: 25} 4LV；ブラウン系
          %option{value: 26} 2LV；ブラウン系
          %option{value: 27} 12LV；マット系
          %option{value: 28} 10LV；マット系
          %option{value: 29} 8LV；マット系
          %option{value: 30} 6LV；マット系
          %option{value: 31} なし
      .error-edit-9
      .edit-item-form
        = f.label :パーマ（必須）,class:"edit-select-label"
        %select.edit-items-select-box{name: "perm_id"}
          %option{value: ""} ----
          %option{value: 1} ホットパーマ(デジパなど)
          %option{value: 2} コールドパーマ(水パなど)
          %option{value: 3} なし
      .error-edit-10
      .actions-edits
        = f.submit "SENT",class:"btn_edit"

app/views/products/index.html.haml
.pickup-contents
  .pickup-title
    .top-title
      ピックアップスタイル
  .genres-link
    .bob-style
      = link_to "ボブ","/stylegenres/1"
    .bob-contents
      - @bob_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}"
    .short-style
      = link_to "ショート","/stylegenres/2"
    .short-contents
      - @short_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"
    .mid-style
      = link_to "ミディアム","/stylegenres/3"

    .mid-contents
      - @mid_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"
    .semlong-style
      = link_to "セミロング","/stylegenres/4"

    .semlong-contents
      - @semlong_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"
    .long-style
      = link_to "ロング","/stylegenres/5"

    .long-contents
      - @long_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"
    .superlong-style
      = link_to "スーパーロング","/stylegenres/6"

    .superlong-contents
      - @superlong_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"
    .hairset-style
      = link_to "ヘアセット","/stylegenres/7"

    .hairset-contents
      - @hairset_style.each do |style|
        .one-index-contents
          .shop_name-index
            店名：
            = style.shop_name
          .video-index-product
            = video_tag style.video_url.to_s,loop: true, controls: true, width: 300,class:"mv"
          %i.far.fa-clipboard.index-icon
            = link_to '詳細',"/products/#{style.id}",class:"stylename"

  = render 'footer'

app/views/products/new.html.haml
.product-new-contents
  .one-new-product
    = form_for @product do |f|
      %h3 掲載する
      .new-form
        = f.label :タイトル（必須）,class:"out-label"
        = f.text_field :title,class:"text-box"
      .error-new-11
      .new-form
        = f.label :店名（必須）,class:"out-label"
        = f.text_field :shop_name,class:"text-box"
      .error-new-1
      .new-form
        = f.label :説明文（必須）,class:"form-label"
        = f.text_field :text,class:"text-box"
      .error-new-2
      .new-form
        = f.label :動画（必須）,class:"video-label"
        = f.file_field :video,class:"video-form"
      .error-new-3
      .new-form
        = f.label :スタイリスト名（必須）,class:"form-label"
        = f.text_field :stylest_name,class:"text-box"
      .error-new-4
      .new-form
        = f.label :コスメ,class:"out-label"
        = f.text_field :cosme,class:"text-box"
      .error-new-9
      .new-form
        = f.label :リンク,class:"out-label"
        = f.text_field :link_url,class:"text-box"
      .error-new-10
      .new-item-form
        = f.label :スタイル（必須）,class:"select-label"
        %select.stylename-select-box{name: "stylegenre_id"}
          %option{value: ""} ----
          %option{value: 1} ボブ
          %option{value: 2} ショート
          %option{value: 3} ミディアム
          %option{value: 4} セミロング
          %option{value: 5} ロング
          %option{value: 6} スーパーロング
          %option{value: 7} ヘアセット
      .error-new-5
      .new-item-form
        = f.label :アイテム（必須）,class:"select-label"
        %select.items-select-box{name: "item_id"}
          %option{value: ""} ----
          %option{value: 1} ストレートアイロン
          %option{value: 2} コテ32mm
          %option{value: 3} コテ28mm
          %option{value: 4} コテ18mm
          %option{value: 5} コテ16mm
          %option{value: 6} ヘアゴム         
          %option{value: 7} なし 
      .error-new-6
      .new-item-form
        = f.label :カラー（必須）,class:"select-label"
        %select.items-select-box{name: "color_id"}
          %option{value: ""} ----
          %option{value: 1} アッシュ系
          %option{value: 2} ブラウン系
          %option{value: 3} レッド系
          %option{value: 4} マット系
          %option{value: 5} バイオレッド系
          %option{value: 6} イエロー系
          %option{value: 7} オレンジ系
          %option{value: 8} なし
      .error-new-7
      .new-item-form
        = f.label :パーマ（必須）,class:"select-label"
        %select.items-select-box{name: "perm_id"}
          %option{value: ""} ----
          %option{value: 1} ホットパーマ
          %option{value: 2} コールドパーマ
          %option{value: 3} なし
      .error-new-8
      .actions-new
        = f.submit "SENT",class:"sent-btn"

app/views/products/search.html.haml
.search-products-contents
  .search-product-title
    .title-name
      スタイル一覧
  .sasasa
    - @products.each do |product|
      .one-search-product
        .shop_name-searchproduct
          店名：
          = product.shop_name
        .video-searchproduct
          = video_tag product.video_url.to_s,loop: true, controls: true, width: 300
        %i.far.fa-clipboard.show-second-icon
          = link_to '詳細',"/products/#{product.id}",class:"stylename"
    .page_tag
      = paginate(@products)

app/views/products/show.html.haml
.show-product-contents
  .video-contents
    = video_tag @product.video_url.to_s,loop: true, controls: true, width: 700, id: "mv" if @product.video.present?

  .show-tweet-name
    投稿者
    = link_to @product.user.nickname,"/users/#{@product.user.id}",class:"tweet-user_name"
    .link_shownav
      - if user_signed_in? && current_user.id == @product.user_id
        = link_to '編集', "/products/#{@product.id}/edit", method: :get,class:"tweet_show-edit"
        = link_to '削除', "/products/#{@product.id}", method: :delete,class:"tweet_show-delete"
    %ul.list-show
      %li
        タイトル　：
        = @product.title
      %li
        説明文　：
        = @product.text
      %li
        店名　：
        = @product.shop_name   
      %li
        コスメ　：
        = @product.cosme
      %li
        リンク　：
        = link_to @product.link_url ,@product.link_url 
      %li
        アイテム　：
        = @item.name
      %li
        スタイリスト　：
        = @product.stylest_name 
      %li
        カラー　：
        = @color.name 
      %li
        パーマ　：
        = @perm.name 
      %li
        スタイル　：
        = @stylegenre.name  
    

app/views/stylegenres/show.html.haml
.user-show-contents
  .nickname-label
    = @name
    の一覧
  .all-show-user
    - @products.each do |product|
      .one-show-content
        .shop_name_contents
          店名：
          = product.shop_name
        .video-user-show
          = video_tag product.video_url.to_s,loop: true, controls: true, width: 300,class:"mv" 
        - if user_signed_in? && current_user.id == product.user_id
          %i.far.fa-clipboard.show-second-icon
            = link_to "詳細", "/products/#{product.id}", method: :get,class:"show-btn"
          %i.far.fa-edit.show-edit-icon
            = link_to '編集', "/products/#{product.id}/edit", method: :get,class:"show-btn"
          %i.far.fa-trash-alt.show-delete-icon
            = link_to '削除', "/products/#{product.id}", method: :delete,class:"show-btn"
        - else
          %i.far.fa-clipboard.show-second-icon
            = link_to "詳細", "/products/#{product.id}", method: :get,class:"show-btn"
    .page-show-user
      = paginate(@products)
      

app/views/users/search.html.haml
.search-user-contents
  .form_user-content
    %input.search-form_input{name: "keyword", type: "text",placeholder:"ユーザーを検索", value: ""}      
  
  .search-div

app/views/users/show.html.haml
.user-show-contents
  .nickname-label
    = @nickname
    さんの投稿一覧
  .all-show-user
    - @products.each do |product|
      .one-show-content
        .shop_name_contents
          店名：
          = product.shop_name
        .video-user-show
          = video_tag product.video_url.to_s,loop: true, controls: true, width: 300,class:"mv" 
        - if user_signed_in? && current_user.id == product.user.id
          %i.far.fa-clipboard.show-second-icon
            = link_to "詳細", "/products/#{product.id}", method: :get,class:"show-btn"
          %i.far.fa-edit.show-edit-icon
            = link_to '編集', "/products/#{product.id}/edit", method: :get,class:"show-btn"
          %i.far.fa-trash-alt.show-delete-icon
            = link_to '削除', "/products/#{product.id}", method: :delete,class:"show-btn"
        - else
          %i.far.fa-clipboard.show-second-icon
            = link_to "詳細", "/products/#{product.id}", method: :get,class:"show-btn"
    .page-show-user
      = paginate(@products)